### PR TITLE
added ca_cert support for connecting to the etcd endpoint via SSL

### LINKED ISSUE #1: Push to a branch failed with 403
Hi, there!
I'd like to add some feature regarding SSL.
I've prepared a branch locally, but can't push it to your repo.
`remote: Permission to cropalato/terraform-provider-etcd.git denied to qurname2.
fatal: unable to access 'https://github.com/cropalato/terraform-provider-etcd.git/': The requested URL returned error: 403`
Could you please open your repo for creating branches and PR?

### PR DESCRIPTION
**Pull request by qurname2**
ca_cert variable was added to be able to connect to the etcd endpoint via SSL

### CODE REVIEW

**Comment by qurname2** [comment]
@cropalato here it is.

**Comment by cropalato** [comment]
Hi @qurname2 ,

Thanks for your PR, but before go on with that, could you, please, let me know if the approach proposed in [README.md](https://github.com/cropalato/terraform-provider-etcd/blob/main/README.md#self-signed-ssl-connection) doesn't works for you?

**Comment by qurname2** [comment]
@cropalato No, it doesn't work and how is it supposed to work if even don't have any code regarding SSL inside ?
`tlsInfo := transport.TLSInfo{
    //transport.TLSInfo
}`
And to my mind, the explicit variable is just a more convenient and natural way to declare ca_cert, isn't it?

**Review by cropalato — APPROVED** [review]
Indeed, Thanks for your help.

**Pull request merged**
