### PR TITLE
Different improvements

### LINKED ISSUE #9: Use a more unique/random setId
I am using the etcd key as ID, should be interesting to replace that for something more unique.

### PR DESCRIPTION
**Pull request by qurname2**
1. Created uuidGenerator function - id for resources should be unique random uuid .
2. removed unused comments
3. Fixed several bugs regarding [permissions](https://github.com/cropalato/terraform-provider-etcd/compare/main...qurname2:different_improvements?expand=1#diff-0dbc864205c96ca84ce622f67c0d1c6ee5233d1af8d11b49b9c72f072867b125R80)
4. Fixed bugs with [return](https://github.com/cropalato/terraform-provider-etcd/compare/main...qurname2:different_improvements?expand=1#diff-0dbc864205c96ca84ce622f67c0d1c6ee5233d1af8d11b49b9c72f072867b125L231) diags

### CODE REVIEW

**Comment by cropalato** [comment]
@qurname2,

Thanks for your contribution.
I didn't test yet, but I understood it will force a new setId every time we run terraform. Is really that what you want? If yes, why?

**Comment by qurname2** [comment]
@cropalato, Hi!
No, it won't force a new setID every time. New setID will be created only for the new resources (how it works right now, but instead of `d.SetId(fmt.Sprintf("%v_%v_%v", role, key, permission))` will be `uuid.NewV4()`)

**Comment by cropalato** [comment]
Hello @qurname2 ,

I am ok with using uuid, that is a good idea thanks.
But I can see `d.SetId(uuidGenerator())` in data_source_* files. That is the part I don't understand.

**Comment by qurname2** [comment]
Hello, @cropalato!
Could you please explain what exactly seems strange to you?
I've replaced `d.SetId(prefix) `-> `d.SetId(uuidGenerator())`

**Comment by cropalato** [comment]
Never mind. I misunderstood the first time I read the code.
Thanks for your help.

**Pull request merged**
